version: '3'
services:
  llm-endpoint:
    build:
      context: ./LLMs-Endpoint
    ports:
      - "5000:5000"
    volumes:
      - ./LLMs-Endpoint/app:/app
  nodejs-server:
    build:
      context: ./BackendAPI-Node
    ports:
      - "4000:4000"
    depends_on:
      - llm-endpoint
  ui-frontend:
    build:
      context: ./UIFrontend
    ports:
      - "3000:3000"
    depends_on:
      - nodejs-server
